version: "3.9"

services:
  loki:
    container_name: loki
    image: grafana/loki:2.3.0
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ./loki/config/:/etc/loki/
      - ./loki/data:/data/loki
    command: -config.file=/etc/loki/loki-config.yaml

  promtail:
    container_name: promtail
    image: grafana/promtail:2.3.0
    restart: unless-stopped
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail/config/:/etc/promtail/
    command: -config.file=/etc/promtail/promtail-config.yaml
    depends_on: 
      - "loki"

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    user: "0"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana

